name: Daily Financial Metrics Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 8:00 AM UTC daily
  workflow_dispatch:      # Allows manual triggers

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas google-api-python-client

    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > creds.json
      
    - name: Run updater
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python financial_metrics_updater.py